import {
  BadRequestException,
  Body,
  Controller,
  Delete,
  ForbiddenException,
  Get,
  Logger,
  NotFoundException,
  Param,
  Post,
  Req,
  Res,
  UploadedFile,
  UseGuards,
  UseInterceptors,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { diskStorage } from 'multer';
import { ZipArchive } from 'archiver';
import type { Request, Response } from 'express';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import type { JwtPayload } from '../auth/auth.service';
import { BarAccessService } from '../bars/bar-access.service';
import { EventsService } from '../events/events.service';
import { EventMediaService } from './event-media.service';
import { CreateEventMediaLinkDto } from './dto/create-event-media-link.dto';
import {
  buildMediaUploadFilename,
  MAX_MEDIA_UPLOAD_BYTES,
  MEDIA_EXTENSION_BY_MIME,
  UPLOADS_DIR,
} from '../bottles/uploads';

@UseGuards(JwtAuthGuard)
@Controller('events/:slug/media')
export class EventMediaController {
  private readonly logger = new Logger(EventMediaController.name);

  constructor(
    private readonly eventMediaService: EventMediaService,
    private readonly eventsService: EventsService,
    private readonly barAccessService: BarAccessService,
  ) {}

  @Get()
  async findAll(@Param('slug') slug: string, @Req() req: Request) {
    const user = req.user as JwtPayload;
    const event = await this.eventsService.findBySlug(slug);
    await this.barAccessService.assertMember(event.barId, user);
    return this.eventMediaService.findForEvent(slug);
  }

  /**
   * Every uploaded photo and video of the soirée as a single zip.
   *
   * Streamed rather than buffered: a gallery can hold hundreds of megabytes of
   * video, and holding that in memory to send it would be a trivial way to take
   * the API down. Declared before any `:id` route so "archive" is not read as
   * a media id.
   */
  @Get('archive')
  async archive(
    @Param('slug') slug: string,
    @Req() req: Request,
    @Res() res: Response,
  ) {
    const user = req.user as JwtPayload;
    const event = await this.eventsService.findBySlug(slug);
    await this.barAccessService.assertMember(event.barId, user);

    const entries = await this.eventMediaService.collectArchiveEntries(slug);
    if (entries.length === 0) {
      throw new NotFoundException(
        'Aucun fichier à télécharger pour cette soirée',
      );
    }

    // The slug is generated by us, so it is safe to interpolate into a header;
    // the event name is user-supplied and would allow header injection.
    res.setHeader('Content-Type', 'application/zip');
    // The slug already reads like "soiree-du-14-juillet-a1b2c3d4"; prefixing it
    // again would ship files named "soiree-soiree-…".
    res.setHeader('Content-Disposition', `attachment; filename="${slug}.zip"`);
    res.setHeader('X-Content-Type-Options', 'nosniff');

    // `store` (no deflate): photos and videos are already compressed, so
    // deflating them burns CPU for roughly nothing.
    const archive = new ZipArchive({ store: true });
    archive.on('warning', (err) =>
      this.logger.warn(`Archive ${slug} : ${err.message}`),
    );
    archive.on('error', (err) => {
      this.logger.error(`Archive ${slug} : ${err.message}`);
      // Headers are already sent by this point, so the only honest signal left
      // is to break the connection and let the client see a truncated file.
      res.destroy(err);
    });

    archive.pipe(res);
    for (const entry of entries) {
      archive.file(entry.path, { name: entry.name });
    }
    await archive.finalize();
  }

  @Post('upload')
  @UseInterceptors(
    FileInterceptor('file', {
      storage: diskStorage({
        destination: UPLOADS_DIR,
        filename: (_req, file, callback) => {
          const filename = buildMediaUploadFilename(file.mimetype);
          if (!filename) {
            return callback(
              new BadRequestException('Type de fichier non autorisé'),
              '',
            );
          }
          callback(null, filename);
        },
      }),
      fileFilter: (_req, file, callback) => {
        if (!MEDIA_EXTENSION_BY_MIME[file.mimetype]) {
          return callback(
            new BadRequestException(
              'Seules les photos (JPEG, PNG, WEBP, GIF) et vidéos (MP4, WEBM, MOV) sont autorisées',
            ),
            false,
          );
        }
        callback(null, true);
      },
      limits: { fileSize: MAX_MEDIA_UPLOAD_BYTES, files: 1 },
    }),
  )
  async upload(
    @Param('slug') slug: string,
    @Req() req: Request,
    @UploadedFile() file: Express.Multer.File,
  ) {
    const user = req.user as JwtPayload;
    if (!file) {
      throw new BadRequestException('Aucun fichier téléchargé');
    }
    const event = await this.eventsService.findBySlug(slug);
    await this.barAccessService.assertMember(event.barId, user);
    return this.eventMediaService.createUpload(slug, user.sub, file);
  }

  @Post('link')
  async createLink(
    @Param('slug') slug: string,
    @Req() req: Request,
    @Body() dto: CreateEventMediaLinkDto,
  ) {
    const user = req.user as JwtPayload;
    const event = await this.eventsService.findBySlug(slug);
    await this.barAccessService.assertMember(event.barId, user);
    return this.eventMediaService.createDriveLink(slug, user.sub, dto.url);
  }

  @Delete(':id')
  async remove(
    @Param('slug') slug: string,
    @Param('id') id: string,
    @Req() req: Request,
  ) {
    const user = req.user as JwtPayload;
    const event = await this.eventsService.findBySlug(slug);
    const { isOwnerOrAdmin } = await this.barAccessService.assertMember(
      event.barId,
      user,
    );
    const media = await this.eventMediaService.findOneForEvent(slug, id);
    if (media.uploaderId !== user.sub && !isOwnerOrAdmin) {
      throw new ForbiddenException(
        "Vous ne pouvez retirer que vos propres médias, ou ceux d'une soirée dont vous êtes l'hôte",
      );
    }
    return this.eventMediaService.remove(slug, id);
  }
}
